services:
  ollama:
    build:
      context: .
      dockerfile: DockerFile
    container_name: ollama-ai
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    # Start server only — model is already downloaded
    command: ollama serve

volumes:
  ollama_data:
